name: Copy Flutter Web Build to Docs

on:
  push:
    branches:
      - main  # Run only when code is pushed to main
      - akash_dev
      - gh-pages
  pull_request:
    branches:
      - main  # Run only when code is pushed to main
      - akash_dev
      - gh-pages
  

jobs:
  build_and_copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.2

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web App
        run: flutter build web

      - name: Copy Build Files to Docs
        run: |
          rm -rf docs  # Remove old docs folder
          mkdir docs   # Create a new docs folder
          cp -r build/web/* docs/  # Copy only contents of build/web

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/
          git commit -m "Automated: Copy build/web contents to docs"
          git push origin HEAD:${{ github.ref }}
